djangomatic/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('<slug:title>', views.article_details, name='details'),
    path('', views.articles_list, name='list'),
]

djangomatic/djangomatic/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls, name='adminpanel'),
    re_path(r'articles/', include('articles.urls')),
    re_path(r'users/', include('users.urls')),
    path('about/', views.about, name='about'),
    path('', views.home, name='home'),
    # re_path(r'', views.notfound),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangomatic/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

djangomatic/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.jpg', blank=True)
    #author

    def __str__(self):
        return self.title

    def snippet(self):
        return (self.body[:50] + '...' if len(self.body) > 50 else self.body)

djangomatic/users/models.py
from django.db import models

# Create your models here.

djangomatic/articles/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Article

# Create your views here.
def articles_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/articles_list.html', {'articles': articles})

def article_details(request, title):
    article = Article.objects.get(slug=title)
    return render(request, 'articles/article_details.html', {'article' : article})

djangomatic/djangomatic/views.py
from django.http import HttpResponse
from django.shortcuts import render
from articles.models import Article

def home(request):
    articles = Article.objects.all().order_by('-date')[:5]
    return render(request, 'home.html', {'articles': articles})

def about(request):
    return render(request, 'about.html')

def notfound(request):
    return render(request, 'notfound.html')

djangomatic/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'users/signup.html', { 'form': form }) 

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', { "form": form })

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

djangomatic/articles/templates/articles/article_details.html
{% extends 'base_template.html' %}

{% block title %} | {{ article.title }}{% endblock %}
{% block content %}
<div id="article_details">
    <img src="{{ article.thumb.url }}" />
    <div class="content">
        <h1>{{ article.title }}</h1>
        <p>{{ article.date }}</p>
        <p>{{ article.body }}</p>
    </div>
</div>
{% endblock %}

djangomatic/articles/templates/articles/articles_list.html
{% extends 'base_template.html' %}

{% block title %} | Articles{% endblock %}
{% block content %}
    <h1>All Articles</h1>
    <div id="articles">
        {% for article in articles %}
            <div class="article">
                <a href="{% url 'articles:details' title=article.slug %}">{{ article.title }}</a>
                <p>{{ article.date }}</p>
                <p>{{ article.snippet }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

djangomatic/templates/about.html
{% extends 'base_template.html' %}

{% block title %} | About{% endblock %}
{% block content %}
    <p>This is a site, created by me while learning Django framework.</p>
    <p>Gazaris @ 2022</p>
{% endblock %}

djangomatic/templates/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
    <title>Djangomatic{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <a href="{% url 'home' %}">
            <div id="logo"></div>
            <h1 class="noselect">Djangomatic</h1>
        </a>
        <a class="navbtn noselect" href="{% url 'articles:list' %}">Articles</a>
        <div id="account" class="noselect">
            <!-- TODO make it change when logged in -->
            <!-- <a href="{% url 'users:signup' %}" class="navbtn">Sign up</a>
            |
            <a href="{% url 'users:login' %}" class="navbtn" id="login-navbtn">Log in</a> -->
            <form action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn navbtn">Log out</button>
            </form>
        </div>
    </header>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

djangomatic/templates/home.html
{% extends 'base_template.html' %}

{% block content %}
    <h1>Latest Articles</h1>
    <div id="articles">
        {% for article in articles %}
            <div class="article">
                <a href="{% url 'articles:details' title=article.slug %}">{{ article.title }}</a>
                <p>{{ article.date }}</p>
                <p>{{ article.snippet }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

djangomatic/templates/notfound.html
{% extends 'base_temlplate.html' %}

{% block title %} | 404 Not Found{% endblock %}

{% block content %}
    <h1>404</h1>
    <h2>Something went wrong...</h2>
{% endblock %}

djangomatic/users/templates/users/login.html
{% extends 'base_template.html' %}

{% block title %} | Login{% endblock %}
{% block content %}
    <h1>Login</h1>
    <form class="signup-form" action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Login">
    </form>
{% endblock %}

djangomatic/users/templates/users/signup.html
{% extends 'base_template.html' %}

{% block title %} | Signup{% endblock %}
{% block content %}
    <h1>Signup</h1>
    <form class="signup-form" action="{% url 'users:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}